name: reflectable
version: 4.0.5
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  analyzer: 6.2.0
  build: ^2.4.1
  build_resolvers: ^2.4.2
  build_config:
  build_runner: ^2.4.7
  build_runner_core: ^7.2.11
  dart_style: ^2.3.4
  glob: ^2.1.2
  logging: ^1.0.0
  package_config: ^2.1.0
  path: ^1.8.0
  source_span: ^1.8.1
dev_dependencies:
  build_test: ^2.2.2
  lints: ^3.0.0
  test:
